# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

transition_function <- function(cell_values, transition_matrix, row_names, col_names) {
    .Call('_cdlsim_transition_function', PACKAGE = 'cdlsim', cell_values, transition_matrix, row_names, col_names)
}

